/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvcJuegoInicio.vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import mvcJuegoIniciado.interfaces.IVista;
import mvcJuegoIniciado.vistas.TableroJuego;
import mvcJuegoInicio.interfaces.IControlJuegoInicio;
import mvcJuegoInicio.interfaces.IModeloLeibleJInicio;
import mvcJuegoInicio.interfaces.IModeloModificableJInicio;

/**
 *
 * @author Ximena
 */
public class PantallaMockJuego extends javax.swing.JFrame implements IVista {
    private final IModeloLeibleJInicio modelo;
    private final IControlJuegoInicio control;

    private JLabel lblTitulo;
    private JLabel lblNombrePartida;
    private JLabel lblNumJugadores;
    private TableroMock tablero;

    /**
     * Creates new form PantallaMockJuego
     */
    public PantallaMockJuego(IModeloLeibleJInicio modelo, IControlJuegoInicio control) {
        this.modelo = modelo;
        this.control = control;
        this.tablero = new TableroMock(modelo);
        
        pantallaMock();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void pantallaMock() {
        setTitle("Timbiriche - Vista Mock");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLayout(new BorderLayout());

        JPanel panelSuperior = new JPanel();
        panelSuperior.setBackground(new Color(40, 40, 40));
        panelSuperior.setPreferredSize(new Dimension(100, 70));

        lblTitulo = new JLabel("Datos de la Partida");
        lblTitulo.setForeground(Color.WHITE);
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 28));

        lblNombrePartida = new JLabel("Partida: " + modelo.getNombrePartida(), SwingConstants.CENTER);
        lblNombrePartida.setForeground(Color.LIGHT_GRAY);
        lblNombrePartida.setFont(new Font("Segoe UI", Font.PLAIN, 18));

        lblNumJugadores = new JLabel("Jugadores: " + modelo.getNumJugadores(), SwingConstants.CENTER);
        lblNumJugadores.setForeground(Color.LIGHT_GRAY);
        lblNumJugadores.setFont(new Font("Segoe UI", Font.PLAIN, 18));

        panelSuperior.add(lblTitulo);
        panelSuperior.add(lblNombrePartida);

        add(panelSuperior, BorderLayout.NORTH);

        // PANEL DE INFO
        JPanel panelInfo = new JPanel();
        panelInfo.setLayout(new FlowLayout(FlowLayout.CENTER, 35, 10));
        panelInfo.setBackground(new Color(245, 245, 245));

        panelInfo.add(lblNumJugadores);

        add(panelInfo, BorderLayout.SOUTH);

        // TABLERO EN CENTRO
        JPanel contenedorTablero = new JPanel(new BorderLayout());
        contenedorTablero.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JScrollPane scroll = new JScrollPane(tablero);
        scroll.setBorder(BorderFactory.createLineBorder(Color.BLACK, 3));

        contenedorTablero.add(scroll, BorderLayout.CENTER);

        add(contenedorTablero, BorderLayout.CENTER);

        pack();
        
//        setTitle("Timbiriche - Juego Mock");
//        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
//        setLayout(new BorderLayout());
//
//        JPanel panelSuperior = new JPanel();
//        panelSuperior.setBackground(new Color(40, 40, 40));
//        panelSuperior.setPreferredSize(new Dimension(100, 70));
//
//        lblTitulo = new JLabel("Pantalla de Juego - Mock");
//        lblTitulo.setForeground(Color.WHITE);
//        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 28));
//        panelSuperior.add(lblTitulo);
//        
//        add(panelSuperior, BorderLayout.NORTH);
//
//        JPanel contenedorTablero = new JPanel(new BorderLayout());
//        contenedorTablero.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
//
//        JScrollPane scroll = new JScrollPane(tablero);
//        scroll.setBorder(BorderFactory.createLineBorder(Color.BLACK, 3));
//        contenedorTablero.add(scroll, BorderLayout.CENTER);
//
//        add(contenedorTablero, BorderLayout.CENTER);
//        
//        pack();
    }
    
    @Override
    public void actualizar() {
        repaint();
        revalidate();
    }

    @Override
    public void mostrar() {
        setVisible(modelo.isMostrandoPantallaMock());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
