/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvcJuegoInicio.vistas;

import Enums.ColorJugador;
import Enums.ImagenJugador;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import utils.ColorConverter;
import utils.GeneradorImagen;

/**
 *
 * @author Ramon Valencia
 */
public class PantallaRegistrarJugador extends javax.swing.JFrame {
    
    private JLabel lblAvatar;
    private JTextField txtNombre;
    private JButton btnAtras;
    private JButton btnContinuar;
    
    private ImagenJugador imagenActual = ImagenJugador.STUART; // ejemplo
    private ColorJugador colorActual = ColorJugador.GRIS;
    
    /**
     * Creates new form RegistrarJugador
     */
    public PantallaRegistrarJugador() {
        generarPantallaRegistrarJugador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void generarPantallaRegistrarJugador() {
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setUndecorated(false);
        setResizable(false);
        setLayout(new BorderLayout());
        setBackground(Color.WHITE);

        // ----- TÍTULO -----
        JLabel lblTitulo = new JLabel("Registrar Jugador", SwingConstants.CENTER);
        lblTitulo.setFont(new Font("SansSerif", Font.BOLD, 32));
        lblTitulo.setBorder(BorderFactory.createEmptyBorder(40, 0, 40, 0));
        add(lblTitulo, BorderLayout.NORTH);

        // ----- PANEL CENTRAL -----
        JPanel centro = new JPanel();
        centro.setBackground(new Color(240, 240, 240));
        centro.setBorder(BorderFactory.createEmptyBorder(40, 40, 40, 40));
        centro.setLayout(new GridBagLayout());

        GridBagConstraints c = new GridBagConstraints();
        c.gridy = 0;

        generarLabelImagen();
        centro.add(lblAvatar, c);

        // Campo de nombre
        c.gridy++;
        txtNombre = new JTextField();
        txtNombre.setPreferredSize(new Dimension(220, 34));
        txtNombre.setFont(new Font("SansSerif", Font.PLAIN, 18));
        txtNombre.setHorizontalAlignment(JTextField.CENTER);

        centro.add(txtNombre, c);

        add(centro, BorderLayout.CENTER);

        // ----- BOTONES -----
        JPanel abajo = new JPanel(new BorderLayout());
        abajo.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        btnAtras = new JButton("Atrás");
        btnContinuar = new JButton("Continuar");

        abajo.add(btnAtras, BorderLayout.WEST);
        abajo.add(btnContinuar, BorderLayout.EAST);

        add(abajo, BorderLayout.SOUTH);
    }
    
    private void generarLabelImagen() {
        int ancho = 120;
        int alto = 120;
        
        lblAvatar = new JLabel();
        lblAvatar.setPreferredSize(new Dimension(ancho, alto));
        lblAvatar.setHorizontalAlignment(SwingConstants.CENTER);
        lblAvatar.setIcon(GeneradorImagen.obtenerImagenJugador(imagenActual, ancho, alto));
        lblAvatar.setBorder(BorderFactory.createLineBorder(ColorConverter.obtenerColorJugador(colorActual), 2, true));

        lblAvatar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblAvatar.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
