/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvcJuegoInicio.vistas;

import Enums.TamañoTablero;
import enums.ObserverType;
import enums.TamañosTablero;
import mvcJuegoIniciado.interfaces.IVista;
import mvcJuegoIniciado.vistas.PantallaInicio;
import mvcJuegoInicio.interfaces.IControlJuegoInicio;

/**
 *
 * @author Ximena
 */
public class PantallaCrearPartida extends javax.swing.JFrame implements IVista {
    private final IControlJuegoInicio control;

    /**
     * Creates new form PantallaCrearPartida
     * @param control
     */
    public PantallaCrearPartida(IControlJuegoInicio control) {
        this.control = control;
        initComponents();
        cargarOpciones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnCrearPartida = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        txtNombrePartida = new javax.swing.JTextField();
        lblNumJugadores = new javax.swing.JLabel();
        cbNumJugadores = new javax.swing.JComboBox<>();
        lblTamañoTablero = new javax.swing.JLabel();
        cbTamañosTablero = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setText("Configurar Partida");

        btnAtras.setBackground(new java.awt.Color(51, 51, 51));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnCrearPartida.setBackground(new java.awt.Color(51, 51, 51));
        btnCrearPartida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCrearPartida.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearPartida.setText("Continuar");
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidaActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setText("Nombre de la partida:");

        txtNombrePartida.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        lblNumJugadores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumJugadores.setText("Número de jugadores:");

        cbNumJugadores.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbNumJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin seleccionar" }));

        lblTamañoTablero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTamañoTablero.setText("Tamaño del tablero:");

        cbTamañosTablero.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbTamañosTablero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin seleccionar" }));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearPartida)
                .addGap(43, 43, 43))
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombrePartida, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumJugadores)
                                    .addComponent(lblTamañoTablero))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbNumJugadores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbTamañosTablero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblTitulo)
                .addGap(73, 73, 73)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombrePartida))
                .addGap(36, 36, 36)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumJugadores)
                    .addComponent(cbNumJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTamañoTablero)
                    .addComponent(cbTamañosTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(btnCrearPartida))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        atras();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidaActionPerformed
        continuar();
    }//GEN-LAST:event_btnCrearPartidaActionPerformed

    private void cargarOpciones() {
        cbNumJugadores.addItem("2");
        cbNumJugadores.addItem("3");
        cbNumJugadores.addItem("4");

        for (TamañosTablero t : TamañosTablero.values()) {
            cbTamañosTablero.addItem(t.name());
        }
    }
    
    private void crearPartida() {
        String nombrePartida = txtNombrePartida.getText();
        
        String jugadores = (String) cbNumJugadores.getSelectedItem();
        int numJugadores = jugadores.equals("Sin seleccionar") ? 0 : Integer.parseInt(jugadores);
        
        String tablero = (String) cbTamañosTablero.getSelectedItem();
        TamañosTablero tamaño = tablero.equals("Sin seleccionar") ? null : TamañosTablero.valueOf(tablero);
        
        control.crearPartida(nombrePartida, numJugadores, tamaño);
    }
    
    private void atras() {
        PantallaInicio inicio = new PantallaInicio();
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);
        this.dispose();
    }
    
    private void continuar() {
        crearPartida();
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JComboBox<String> cbNumJugadores;
    private javax.swing.JComboBox<String> cbTamañosTablero;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumJugadores;
    private javax.swing.JLabel lblTamañoTablero;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtNombrePartida;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar() {
        this.setVisible(false);
        // control.mostrarVista(ObserverType.PANTALLA_JUEGO);
    }

    @Override
    public void mostrar() {
        this.setVisible(true);
    }
}
